name: Release Draft

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: aeolun/release-wizard@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          versionPrefix: v
          tagPrefix: ''
          templatePath: release-template.md 
